# -----------------------------
# Application
# -----------------------------
spring.application.name=simulator

# -----------------------------curl kafka90
# Kafka
# -----------------------------
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

# -----------------------------
# Kafka topic
# -----------------------------
kafka.topic.requested=market-requested
kafka.topic.referred=market-referred

# -----------------------------
# Simulator config
# -----------------------------
simulator.categories=10
simulator.manufacturers=36
simulator.products-per-category=12
simulator.popularity-range=20-120
simulator.generate-interval-ms=1500
simulator.click-probability=0.30
simulator.active-categories-per-tick=2
simulator.min-traffic-per-tick=80
simulator.max-traffic-per-tick=220
simulator.promo-duration-ticks=18
simulator.promo-boost-multiplier=2.2
simulator.auto-promo-probability=0.08
simulator.trend-duration-ticks=24
